=== benaiah97/project/Source/gatewaywar/src/main/webapp/QueryTicketAnswer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Andrea Martinotti (OmniTicket Network Administration) -->
<!--Copyright Notice: This document (written or otherwise displayed on magnetic media or other medium) contains confidential and proprietary information of OmniTicket Network, Inc. 
	or its affiliates. It has been furnished only for informational purposes, and no license or permission is hereby granted to use such information in any manner. In no event may this 
	information be reproduced, distributed and/or publicly displayed in any form or by any means without prior expressed written permission of OmniTicket Network, Inc. All rights reserved. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Command">
		<xs:annotation>
			<xs:documentation>Message Format Answer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:annotation>
						<xs:documentation>Recap information on Message type</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ReferenceNumber">
								<xs:annotation>
									<xs:documentation>Incoming </xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RequestNumber" type="xs:integer">
								<xs:annotation>
									<xs:documentation>Match the Incoming Request Number</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="SessionId" type="xs:integer">
								<xs:annotation>
									<xs:documentation>Session Id
										One for each new Login where managed
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="RequestType">
								<xs:annotation>
									<xs:documentation>Command Group
										Command group type
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Query" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RequestSubType">
								<xs:annotation>
									<xs:documentation>Command subtype
										Detailed command
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="QueryTicket" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ValueMsg">
								<xs:annotation>
									<xs:documentation>Value messages Group
										Only on answer Messages
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ValuedQty" type="xs:integer" />
										<xs:element name="NonValuedQty" type="xs:integer" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="QueryTicket">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Error">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ErrorCode" type="xs:integer">
											<xs:annotation>
												<xs:documentation>0 = no error</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="ErrorShortDescription" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="25" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ErrorDescription" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Error Description</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TicketInfo" minOccurs="0" maxOccurs="8">
								<xs:annotation>
									<xs:documentation>Ticket Info Group</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Item">
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="1" />
													<xs:maxInclusive value="8" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ItemStatus">
											<xs:annotation>
												<xs:documentation>Item Result Code</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:maxInclusive value="65000" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TicketType" type="xs:integer" minOccurs="0" />
										<xs:element name="Price" type="xs:float" minOccurs="0" />
										<xs:element name="Tax" type="xs:float" minOccurs="0" />
										<xs:element name="Ticket">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="TDSSN" minOccurs="0">
														<xs:annotation>
															<xs:documentation>String Code</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Site">
																	<xs:annotation>
																		<xs:documentation>Site String</xs:documentation>
																	</xs:annotation>
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="3" />
																			<xs:maxLength value="3" />
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Station">
																	<xs:annotation>
																		<xs:documentation>Station String</xs:documentation>
																	</xs:annotation>
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="6" />
																			<xs:maxLength value="6" />
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Date" type="xs:string">
																	<xs:annotation>
																		<xs:documentation>Date String</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="TicketId" type="xs:string">
																	<xs:annotation>
																		<xs:documentation>Ticket string</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="TCOD" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Numeric Code</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="17" />
																<xs:maxLength value="17" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="BarCode" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Ticket Barcode</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="21" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="MagCode" minOccurs="0">
														<xs:annotation>
															<xs:documentation>Mag Track 1</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="73" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="ExternalTicketCode" minOccurs="0">
														<xs:annotation>
															<xs:documentation>External ticket code
																(phase 2)
															</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="20" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="RemainingValue" type="xs:float" minOccurs="0" />
										<xs:element name="VoidCode" type="xs:integer" minOccurs="0" />
										<xs:element name="Validity" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Validity at the gate</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="StartDate" type="xs:string">
														<xs:annotation>
															<xs:documentation>Start Date at gates</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="EndDate" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="TicketFlag" minOccurs="0">
											<xs:complexType>
												<xs:sequence maxOccurs="unbounded">
													<xs:element name="TicketFlagNumber" type="xs:integer">
														<xs:annotation>
															<xs:documentation>Ticket Flag
																TF001 table
															</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Usages" minOccurs="0" maxOccurs="100">
											<xs:complexType>
												<xs:sequence minOccurs="0">
													<xs:element name="Item">
														<xs:simpleType>
															<xs:restriction base="xs:integer">
																<xs:minInclusive value="1" />
																<xs:maxInclusive value="100" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="UsageType" type="xs:integer">
														<xs:annotation>
															<xs:documentation>Usage Type
																UT001 Table
															</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="SiteNumber" type="xs:integer" />
													<xs:element name="Gate" type="xs:string">
														<xs:annotation>
															<xs:documentation>Service Id</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="Date" type="xs:string" />
													<xs:element name="Time" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="TicketAttribute" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Attribute information (number)</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:maxInclusive value="65000" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TicketNote" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Note linked to a ticket, if one</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="25" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="BiometricLevel" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Level of biometric check
													See BL001 table
												</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minInclusive value="0" />
													<xs:maxInclusive value="9" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="TransactionDSSN" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Transaction Id</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Site">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="3" />
																<xs:minLength value="3" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Station">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="6" />
																<xs:maxLength value="6" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Date" type="xs:string" />
													<xs:element name="TransactionId" type="xs:integer">
														<xs:annotation>
															<xs:documentation>Transaction Number</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="TransactionCOD" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="17" />
													<xs:maxLength value="17" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="GroupQuantity" type="xs:integer" minOccurs="0" />
										<xs:element name="TaxExempt" type="xs:boolean" minOccurs="0" />
										<xs:element name="AlreadyUsed" type="xs:boolean" minOccurs="0" />
										<xs:element name="DebitCardAuth" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Credit" type="xs:float" />
													<xs:element name="Debit" type="xs:float" />
													<xs:element name="Balance" type="xs:float" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="BiometricInfo" minOccurs="0" maxOccurs="3">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="DeviceType">
														<xs:simpleType>
															<xs:restriction base="xs:byte">
																<xs:minInclusive value="1" />
																<xs:maxInclusive value="3" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="BiometricTemplate">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2004" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== benaiah97/project/Source/gatewaysvc/src/test/resources/xml/wdw/WDW_Queryticket_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QueryTicketAnswer.xsd">
	<Header>
		<ReferenceNumber> 12345678</ReferenceNumber>
		<RequestNumber>7654321</RequestNumber>
		<SessionId>7777777</SessionId>
		<RequestType>Query</RequestType>
		<RequestSubType>QueryTicket</RequestSubType>
		<ValueMsg>
			<ValuedQty>10</ValuedQty>
			<NonValuedQty>0</NonValuedQty>
		</ValueMsg>
	</Header>
	<QueryTicket>
		<Error>
			<ErrorCode>0</ErrorCode>
			<ErrorShortDescription>OP_FAIL_CC_PAYM_NOT_APP</ErrorShortDescription>
			<ErrorDescription>CREDIT CARD PAYMENT NOT APPROVED</ErrorDescription>
		</Error>
		<TicketInfo>
			<Item>1</Item>
			<ItemStatus>0</ItemStatus>
			<TicketType>25834</TicketType>
			<Price>239.63</Price>
			<Tax>14.63</Tax>
			<Ticket>
				<TDSSN>
					<Site>WDW</Site>
					<Station>CAS999</Station>
					<Date>09-06-15</Date>
					<TicketId>303</TicketId>
				</TDSSN>
				<TCOD>99999999999999999</TCOD>
				<BarCode>77777777777777777777</BarCode>
				<MagCode> FFFFFFFFFFFFFFFFFFFFFFFF </MagCode>
				<ExternalTicketCode>ABCDEFGHIJKLMNOPQRSTUVWXYZ</ExternalTicketCode>
			</Ticket>
			<RemainingValue>350.48</RemainingValue>
			<VoidCode>0</VoidCode>
			<Validity>
				<StartDate>09-06-15</StartDate>
				<EndDate>30-12-31</EndDate>
			</Validity>
			<TicketFlag>
				<TicketFlagNumber>0</TicketFlagNumber>
			</TicketFlag>
			<Usages>
				<Item>1</Item>
				<UsageType>4</UsageType>
				<SiteNumber>93</SiteNumber>
				<Gate>9</Gate>
				<Date>09-06-28</Date>
				<Time>16:17</Time>
			</Usages>
			<Usages>
				<Item>2</Item>
				<UsageType>4</UsageType>
				<SiteNumber>93</SiteNumber>
				<Gate>9</Gate>
				<Date>09-06-28</Date>
				<Time>16:17</Time>
			</Usages>
			<TicketAttribute>0</TicketAttribute>
			<TicketNote>I AM A TICKET NOTE</TicketNote>
			<BiometricLevel>0</BiometricLevel>
			<TransactionDSSN>
				<Site>WST</Site>
				<Station>CAS005</Station>
				<Date>09-06-28</Date>
				<TransactionId>3</TransactionId>
			</TransactionDSSN>
			<TransactionCOD>99999999999999999</TransactionCOD>
			<GroupQuantity>0</GroupQuantity>
			<TaxExempt>0</TaxExempt>
			<AlreadyUsed>1</AlreadyUsed>
		</TicketInfo>
	</QueryTicket>
</Command>
