=== benaiah97/project/Source/gatewaywar/src/main/webapp/UpdateTransactionAnswer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Copyright Notice: This document (written or otherwise displayed on magnetic media or other medium) contains confidential and proprietary information of OmniTicket Network, Inc. 
	or its affiliates. It has been furnished only for informational purposes, and no license or permission is hereby granted to use such information in any manner. In no event may this 
	information be reproduced, distributed and/or publicly displayed in any form or by any means without prior expressed written permission of OmniTicket Network, Inc. All rights reserved. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Command">
		<xs:annotation>
			<xs:documentation>Message Format Answer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:annotation>
						<xs:documentation>Recap information on Message type</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ReferenceNumber">
								<xs:annotation>
									<xs:documentation>Incoming </xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RequestNumber" type="xs:integer">
								<xs:annotation>
									<xs:documentation>Match the Incoming Request Number</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="SessionId" type="xs:integer">
								<xs:annotation>
									<xs:documentation>Session Id
										One for each new Login where managed
									</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="RequestType">
								<xs:annotation>
									<xs:documentation>Command Group
										Command group type
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Create" />
										<xs:enumeration value="Query" />
										<xs:enumeration value="Void" />
										<xs:enumeration value="Upgrade" />
										<xs:enumeration value="Update" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RequestSubType">
								<xs:annotation>
									<xs:documentation>Command subtype
										Detailed command
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="CreateTransaction" />
										<xs:enumeration value="QueryProduct" />
										<xs:enumeration value="QueryTransaction" />
										<xs:enumeration value="QueryTicket" />
										<xs:enumeration value="UpgradeTicket" />
										<xs:enumeration value="UpdateTransaction" />
										<xs:enumeration value="VoidTicket" />
										<xs:enumeration value="VoidTransaction" />
										<xs:enumeration value="UpdateTicket" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ValueMsg">
								<xs:annotation>
									<xs:documentation>Value messages Group
										Only on answer Messages
									</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ValuedQty" type="xs:integer" />
										<xs:element name="NonValuedQty" type="xs:integer" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="UpdateTransaction">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Error">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ErrorCode" type="xs:integer">
											<xs:annotation>
												<xs:documentation>0 = no error</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="ErrorShortDescription" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="25" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ErrorDescription" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Error Description</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== benaiah97/project/Source/gatewaysvc/src/test/resources/xml/wdw/WDW_CreateTransaction_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<Command xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UpdateTransactionAnswer.xsd">
	<Header>
		<ReferenceNumber> 12345678</ReferenceNumber>
		<RequestNumber>7654321</RequestNumber>
		<SessionId>7777777</SessionId>
		<RequestType>Update</RequestType>
		<RequestSubType>CreateTransaction</RequestSubType>
		<ValueMsg>
			<ValuedQty>10</ValuedQty>
			<NonValuedQty>0</NonValuedQty>
		</ValueMsg>
	</Header>
	<CreateTransaction>
		<Error>
			<ErrorCode>0</ErrorCode>
			<ErrorShortDescription>OP_FAIL_CC_PAYM_NOT_APP</ErrorShortDescription>
			<ErrorDescription>CREDIT CARD PAYMENT NOT APPROVED</ErrorDescription>
		</Error>
	</CreateTransaction>
</Command>
