=== benaiah97/project/Source/config/schemas/update_transaction_response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--TiXML 1.0  12/17/02  Copyright The Walt Disney Company-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
	<xs:element name="Transmission">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Payload">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="PayloadHeader"/>
							<xs:element name="Command" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="CommandHeader"/>
										<xs:element ref="UpdateTransactionResponse"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PayloadHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PayloadID" type="xs:string"/>
				<xs:element name="TSPayloadID" type="xs:string"/>
				<xs:element name="Target" type="xs:string"/>
				<xs:element name="Version" type="xs:string"/>
				<xs:element name="Priority" type="xs:string" minOccurs="0"/>
				<xs:element name="ProcMethod" type="xs:string" minOccurs="0"/>
				<xs:element name="Comm">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Protocol" type="xs:string"/>
							<xs:element name="Method" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TransmitDate" type="xs:date"/>
				<xs:element name="TransmitTime" type="xs:time"/>
				<xs:element name="TktBroker" type="xs:string"/>
				<xs:element name="CommandCount" type="xs:integer"/>
				<xs:element name="PayloadNote" type="xs:string" minOccurs="0"/>
				<xs:element name="PayloadError" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="HdrErrorCode" type="xs:integer"/>
							<xs:element name="HdrErrorType" type="xs:string"/>
							<xs:element name="HdrErrorClass" type="xs:string"/>
							<xs:element name="HdrErrorText" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CommandHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CmdItem" type="xs:integer"/>
				<xs:element name="CmdDuration" type="xs:decimal"/>
				<xs:element name="CmdDate" type="xs:date"/>
				<xs:element name="CmdTime" type="xs:time"/>
				<xs:element name="CmdNote" type="xs:string" minOccurs="0"/>
				<xs:element name="CmdError" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CmdErrorCode" type="xs:integer"/>
							<xs:element name="CmdErrorType" type="xs:string"/>
							<xs:element name="CmdErrorClass" type="xs:string"/>
							<xs:element name="CmdErrorText" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UpdateTransactionResponse" type="xs:string"/>
</xs:schema>

=== benaiah97/project/Config/UpdateTransaction/UpdateTransaction_01_Rsp_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<Transmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\var\opt\apps\RT\schemas\update_transaction_response.xsd">
	<Payload>
		<PayloadHeader>
			<PayloadID>99999999999999999999</PayloadID>
			<TSPayloadID> 8888888</TSPayloadID>
			<Target>PROD-WDW</Target>
			<Version>1.0</Version>
			<Comm>
				<Protocol>IP</Protocol>
				<Method>Network</Method>
			</Comm>
			<TransmitDate>2009-01-23</TransmitDate>
			<TransmitTime>11:38:20.123</TransmitTime>
			<TktBroker>DTI01</TktBroker>
			<CommandCount>1</CommandCount>
		</PayloadHeader>
		<Command>
			<CommandHeader>
				<CmdItem>1</CmdItem>
				<CmdDuration>0.00</CmdDuration>
				<CmdDate>2009-01-23</CmdDate>
				<CmdTime>11:38:20.456</CmdTime>
			</CommandHeader>
			<UpdateTransactionResponse/>
		</Command>
	</Payload>
</Transmission>
