=== benaiah97/project/Source/gatewaywar/docker/xsd/upgrade_alpha_request.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp1 (x64) (http://www.altova.com) by James Todd Lewis (WALT DISNEY WORLD RESORT) -->
<!--TiXML 1.0  12/17/02  Copyright The Walt Disney Company-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
	<xs:element name="Transmission">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Payload">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="PayloadHeader"/>
							<xs:element name="Command">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="CommandHeader"/>
										<xs:element ref="UpgradeAlphaRequest" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PayloadHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PayloadID">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="12"/>
							<xs:maxLength value="20"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Target">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="4"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Version">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="3"/>
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Priority" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="ProcMethod" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI </xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Comm">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Protocol" type="xs:string"/>
							<xs:element name="Method" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="TransmitDate" type="xs:date"/>
				<xs:element name="TransmitTime" type="xs:string"/>
				<xs:element name="TktSeller">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="TSMAC">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TSSystem" type="xs:string"/>
							<xs:element name="TSLocation">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TSSecurity" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="PostHdrWork" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CommandCount" type="xs:integer"/>
				<xs:element name="PayloadNote" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CommandHeader">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CmdItem" type="xs:integer"/>
				<xs:element name="CmdProcRule" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Rule" type="xs:string"/>
							<xs:element name="Value" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CmdTimeout" type="xs:integer" minOccurs="0"/>
				<xs:element name="CmdDate" type="xs:date"/>
				<xs:element name="CmdTime" type="xs:string"/>
				<xs:element name="CmdInvoice" type="xs:string"/>
				<xs:element name="CmdDevice" type="xs:string"/>
				<xs:element name="CmdOperator" type="xs:string"/>
				<xs:element name="CmdActor" type="xs:string" minOccurs="0"/>
				<xs:element name="CmdSecurity" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CmdNote" type="xs:string" minOccurs="0"/>
				<xs:element name="CmdMarket" type="xs:string" minOccurs="0"/>
				<xs:element name="CmdAttribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AttribName" type="xs:string"/>
							<xs:element name="AttribValue" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UpgradeAlphaRequest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ticket" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="TktItem" type="xs:integer"/>
							<xs:element name="ProdCode" type="xs:string"/>
							<xs:element name="ProdPrice" type="xs:string" minOccurs="0"/>
							<xs:element name="TktID">
								<xs:complexType>
									<xs:choice>
										<xs:element name="Mag">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="MagTrack1" type="xs:string"/>
													<xs:element name="MagTrack2" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Barcode" type="xs:string"/>
										<xs:element name="TktDSSN">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="TktDate" type="xs:date"/>
													<xs:element name="TktSite" type="xs:string"/>
													<xs:element name="TktStation" type="xs:string"/>
													<xs:element name="TktNbr" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="TktNID" type="xs:string"/>
										<xs:element name="External" type="xs:string"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="TktStatus" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Not supported by DTI</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="StatusItem" type="xs:string"/>
										<xs:element name="StatusValue" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TktValidity" minOccurs="0">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="ValidStart" type="xs:date" minOccurs="0"/>
										<xs:element name="ValidEnd" type="xs:date" minOccurs="0"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="TktSecurity" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Not supported by DTI</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="Type" type="xs:string" minOccurs="0"/>
										<xs:element name="Level" type="xs:string" minOccurs="0"/>
										<xs:element name="Template" type="xs:string" minOccurs="0"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="TktShell" type="xs:string" minOccurs="0"/>
							<xs:element name="TktMarket" type="xs:string" minOccurs="0"/>
							<xs:element name="TktGroupSize" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Not supported by DTI</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="TktNote" type="xs:string" minOccurs="0"/>
							<xs:element name="TktDemoData" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Not supported by DTI</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="Name" type="xs:string" use="optional"/>
									<xs:attribute name="Last" type="xs:string" use="optional"/>
									<xs:attribute name="First" type="xs:string" use="optional"/>
									<xs:attribute name="Addr1" type="xs:string" use="optional"/>
									<xs:attribute name="Addr2" type="xs:string" use="optional"/>
									<xs:attribute name="City" type="xs:string" use="optional"/>
									<xs:attribute name="State" type="xs:string" use="optional"/>
									<xs:attribute name="Zip" type="xs:string" use="optional"/>
									<xs:attribute name="Country" type="xs:string" use="optional"/>
									<xs:attribute name="Telephone" type="xs:string" use="optional"/>
									<xs:attribute name="DOB" type="xs:string" use="optional"/>
									<xs:attribute name="Email" type="xs:string" use="optional"/>
									<xs:attribute name="Gender" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Payment" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PayItem" type="xs:string"/>
							<xs:element name="PayType">
								<xs:complexType>
									<xs:choice>
										<xs:element name="Cash" type="xs:string">
											<xs:annotation>
												<xs:documentation>Not supported by DTI</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="CreditLine" type="xs:string">
											<xs:annotation>
												<xs:documentation>Not supported by DTI</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="CreditCard">
											<xs:complexType>
												<xs:choice>
													<xs:element name="CCManual">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="CCNbr" type="xs:string"/>
																<xs:element name="CCExpiration">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:length value="4"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="CCVV" type="xs:string" minOccurs="0"/>
																<xs:element name="CCName" type="xs:string" minOccurs="0"/>
																<xs:element name="CCStreet" type="xs:string" minOccurs="0"/>
																<xs:element name="CCZipcode" type="xs:string" minOccurs="0"/>
																<xs:element name="CCCAVV" type="xs:string" minOccurs="0"/>
																<xs:element name="CCEcommerce" type="xs:string" minOccurs="0"/>
																<xs:element name="CCType" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="CCSwipe">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="CCTrack1" type="xs:string"/>
																<xs:element name="CCTrack2" type="xs:string"/>
																<xs:element name="CCVV" type="xs:string" minOccurs="0"/>
																<xs:element name="PosTerminal" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="4"/>
																			<xs:maxLength value="4"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="ExtnlDevSerial" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:maxLength value="16"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="CCWireless">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="CCTrack1" type="xs:string"/>
																<xs:element name="CCTrack2" type="xs:string"/>
																<xs:element name="CCVV" type="xs:string" minOccurs="0"/>
																<xs:element name="PosTerminal" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="4"/>
																			<xs:maxLength value="4"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="ExtnlDevSerial" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="1"/>
																			<xs:maxLength value="16"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="DisneyDollars" type="xs:string">
											<xs:annotation>
												<xs:documentation>Not supported by DTI</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="JobNbr" type="xs:string">
											<xs:annotation>
												<xs:documentation>Not supported by DTI</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Voucher">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="MainCode" type="xs:string"/>
													<xs:element name="UniqueCode" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="GiftCard">
											<xs:complexType>
												<xs:choice>
													<xs:element name="GCManual">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="GCNbr" type="xs:string"/>
																<xs:element name="GCStartDate" type="xs:date" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="GCSwipe">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="GCTrack1" type="xs:string" minOccurs="0"/>
																<xs:element name="GCTrack2" type="xs:string"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="PayAmount" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Eligibility" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Group" type="xs:string"/>
							<xs:element name="Member" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Client" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ClientType" type="xs:string"/>
							<xs:element name="ClientID" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="SalesRep" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Agency" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Not supported by DTI</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="IATA" type="xs:string"/>
							<xs:element name="OTA" type="xs:string"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="IncludeVisualId" type="xs:boolean" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Defaults to false</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== benaiah97/project/Test/UpgradeAlpha/UpgradeAlpha_02_Req_XML.xml
<?xml version="1.0"?>
<Transmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/var/opt/apps/RT/schemas/upgrade_alpha_request.xsd">
	<Payload>
		<PayloadHeader>
			<PayloadID>99999999999999999999</PayloadID>
			<Target>PROD-WDW</Target>
			<Version>1.0</Version>
			<Comm>
				<Protocol>IP</Protocol>
				<Method>Network</Method>
			</Comm>
			<TransmitDate>2009-01-23</TransmitDate>
			<TransmitTime>11:38:20.123</TransmitTime>
			<TktSeller>
				<TSMAC>TSMACTSMAC</TSMAC>
				<TSSystem>CC</TSSystem>
				<TSLocation>A352R</TSLocation>
				<TSSecurity>WaltDisney1</TSSecurity>
			</TktSeller>
			<CommandCount>1</CommandCount>
		</PayloadHeader>
		<Command>
			<CommandHeader>
				<CmdItem>1</CmdItem>
				<CmdTimeout>45</CmdTimeout>
				<CmdDate>2009-01-23</CmdDate>
				<CmdTime>11:38:20.456</CmdTime>
				<CmdInvoice>942871739062978</CmdInvoice>
				<CmdDevice>DEVICE</CmdDevice>
				<CmdOperator>BOBSMITH</CmdOperator>
				<CmdActor>MGR</CmdActor>
				<CmdNote>This is a command note.</CmdNote>
				<CmdMarket>32832</CmdMarket>
				<CmdAttribute>
					<AttribName>AttributeNameOne</AttribName>
					<AttribValue>AttributeValueOne</AttribValue>
				</CmdAttribute>
				<CmdAttribute>
					<AttribName>AttributeNameTwo</AttribName>
					<AttribValue>AttributeValueTwo</AttribValue>
				</CmdAttribute>
			</CommandHeader>
			<UpgradeAlphaRequest>
				<Ticket>
					<TktItem>1</TktItem>
					<ProdCode>PRD11</ProdCode>
					<ProdPrice>500.05</ProdPrice>
					<TktID>
                        <TktDSSN>
                            <TktDate>2008-11-01</TktDate>
                            <TktSite>WMK</TktSite>
                            <TktStation>111</TktStation>
                            <TktNbr>222</TktNbr>
                        </TktDSSN>
					</TktID>
					<TktShell>78</TktShell>
				</Ticket>				
				<Ticket>
					<TktItem>2</TktItem>
					<ProdCode>PRD11</ProdCode>
					<ProdPrice>500.05</ProdPrice>
					<TktID>
						<Mag>
							<MagTrack1> BBBBBBBBBBBBBBBBBB </MagTrack1>
							<MagTrack2>22=222222</MagTrack2>
						</Mag>
					</TktID>
					<TktShell>78</TktShell>
					<TktMarket>32832</TktMarket>
					<TktNote>This is a ticket note</TktNote>
				</Ticket>
				<Ticket>
					<TktItem>3</TktItem>
					<ProdCode>PRD11</ProdCode>
					<ProdPrice>500.05</ProdPrice>
					<TktID>
						<Barcode>33333333333333333333</Barcode>
					</TktID>
					<TktShell>78</TktShell>
				</Ticket>
				<Ticket>
					<TktItem>4</TktItem>
					<ProdCode>PRD11</ProdCode>
					<ProdPrice>500.05</ProdPrice>
					<TktID>
						<TktNID>44444444444444444</TktNID>
					</TktID>
					<TktShell>78</TktShell>
				</Ticket>
				<Ticket>
					<TktItem>5</TktItem>
					<ProdCode>PRD11</ProdCode>
					<ProdPrice>500.05</ProdPrice>
					<TktID>
						<External>5555555555555555</External>
					</TktID>
					<TktShell>78</TktShell>
				</Ticket>
			</UpgradeAlphaRequest>
		</Command>
	</Payload>
</Transmission>

=== benaiah97/project/Source/gatewaysvc/src/test/resources/xml/dti/DLR-UpgradeAlphaRequest-VLINK.xml
<?xml version="1.0" ?>
<Transmission xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/var/opt/apps/RT/schemas/upgrade_alpha_request.xsd">
	<Payload>
		<PayloadHeader>
			<PayloadID>4231245126936660</PayloadID>
			<Target>Prod-DLR</Target>
			<Version>1.0</Version>
			<Comm>
				<Protocol>IP</Protocol>
				<Method>NETWORK</Method>
			</Comm>
			<TransmitDate>2009-06-25</TransmitDate>
			<TransmitTime>11:17:09.266</TransmitTime>
			<TktSeller>
				<TSMAC>VLINK</TSMAC>
				<TSSystem>VLINK</TSSystem>
				<TSLocation>97016000002</TSLocation>
				<TSSecurity>VLINK</TSSecurity>
			</TktSeller>
			<CommandCount>1</CommandCount>
		</PayloadHeader>
		<Command>
			<CommandHeader>
				<CmdItem>1</CmdItem>
				<CmdTimeout>30</CmdTimeout>
				<CmdDate>2009-06-25</CmdDate>
				<CmdTime>08:17:08.00</CmdTime>
				<CmdInvoice>1460467</CmdInvoice>
				<CmdDevice>3</CmdDevice>
				<CmdOperator>00000000</CmdOperator>
			</CommandHeader>
			<UpgradeAlphaRequest>
				<Ticket>
					<TktItem>1</TktItem>
					<ProdCode>113163</ProdCode>
					<ProdPrice>99.00</ProdPrice>
					<TktID>
						<External>6052742643077765</External>
					</TktID>
				</Ticket>
			</UpgradeAlphaRequest>
		</Command>
	</Payload>
</Transmission>
